export const GET_RESOURCES = "GET_RESOURCES";
export const GET_RESOURCE = "GET_RESOURCE";
export const RESOURCES_LOADING = "RESOURCES_LOADING";
export const SEARCH_QUERY = "SEARCH_QUERY";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const USER_LOADING = "USER_LOADING";

